### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by jleppert** [antoviaque/backbone-relational-tutorial#7]
backbone-relational-tutorial]$ node app

/Users/jleppert/devel/backbone-relational-tutorial/node_modules/mongoose/lib/schema.js:276
      throw new TypeError('Invalid value for schema Array path `'+ prefix + ke
            ^
TypeError: Invalid value for schema Array path `messages`
    at Schema.add (/Users/jleppert/devel/backbone-relational-tutorial/node_modules/mongoose/lib/schema.js:276:13)
    at new Schema (/Users/jleppert/devel/backbone-relational-tutorial/node_modules/mongoose/lib/schema.js:87:10)
    at Object.<anonymous> (/Users/jleppert/devel/backbone-relational-tutorial/models.js:13:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jleppert/devel/backbone-relational-tutorial/app.js:33:14)

**Comment by antoviaque** [comment]
@jleppert I don't have a lot of time to maintain this anymore - if I gave you commit access, would you be willing to fix this?

**Comment by jleppert** [comment]
Sure, or I can send you a pull request tomorrow

**Comment by gavinprice** [comment]
Are you guys gonna fix this @jleppert or @antoviaque ??

**Comment by antoviaque** [comment]
@gavinprice As mentioned above I don't have time for maintening this - but I've just given you collaborator rights @jleppert if you still want to fix this. Thank you btw : )

**Comment by SeaBassTian** [comment]
I got the same errors as JL while running app.js. If any1 gets around to fixing this, please let me know.

**Comment by jleppert** [comment]
A simple fix is to remove the version carets from the included package.json dependencies, remove your node modules directory and reinstall the modules. It works with the older versions.

**Comment by webbrain-one** [comment]
Hi there! 👋

I've opened a PR to fix this startup error: https://github.com/antoviaque/backbone-relational-tutorial/pull/10

The issue was caused by an invalid schema definition for the `messages` array path in Mongoose. This PR corrects the schema definition so the app runs without errors.

Thanks for reporting!
